

name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use latest version

      - name: Set up Node.js (Use Latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Client Dependencies
        working-directory: mern-ci-example/client
        run: npm ci  # Faster and more reliable than npm install

      - name: Build Client
        working-directory: mern-ci-example/client
        run: npx vite build  # Use npx to find Vite properly

      - name: Install Server Dependencies
        working-directory: mern-ci-example/server
        run: npm ci  # Ensures clean dependency install

      - name: Build Server
        working-directory: mern-ci-example/server
        run: npm run build
