name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            mern-ci-example/client/package-lock.json
            mern-ci-example/server/package-lock.json

      - name: Install Client Dependencies
        working-directory: mern-ci-example/client
        run: npm ci

      - name: Build Client
        working-directory: mern-ci-example/client
        env:
          NODE_ENV: production
        run: npm run build

      - name: Install Server Dependencies
        working-directory: mern-ci-example/server
        run: npm ci

      - name: Build Server (Optional)
        working-directory: mern-ci-example/server
        run: npm run build

    #   - name: Run Server Tests (If available)
    #     working-directory: mern-ci-example/server
    #     run: npm test
