name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install and Build Client
      - name: Install Client Dependencies
        run: |
          cd mern-ci-example
          cd client
          npm install

      - name: Build Client
        run: |
          cd mern-ci-example
          cd client
          npm run build

      # Install and Build Server
      - name: Install Server Dependencies
        run: |
          cd mern-ci-example
          cd server
          npm install

      - name: Build Server
        run: |
          cd mern-ci-example
          cd server
          npm run build
